____
Amazon Simple Email Service (Amazon SES) is a cloud-based email sending service designed to help digital marketers and application developers send marketing, notification, and transactional emails. It is a reliable, cost-effective service for businesses of all sizes that use email to keep in contact with their customers.
____

Add a dependency to AWS SES SDK:

[source,java]
.build.gradle
----
include::{sourceDir}/build.gradle[tag=awsses,indent=0]
----

Create service which uses AWS Simple Email Service client to send the email

[source,java]
.src/main/java/example/micronaut/AwsSesMailService.java
----
include::{sourceDir}/src/main/java/example/micronaut/AwsSesMailService.java[]
----

<1> Use `javax.inject.Singleton` to designate a class a a singleton
<2> Bean will not loaded unless condition is met.
<3> In case of multiple possible interface implementations of `EmailService`, `@Secondary` reduces the priority.
<4> Values for region and source email are resolved from environment variables or system properties.

We annotated the previous class with `@Requires(condition = AwsResourceAccessCondition.class)`.

The `AwsResourceAccessCondition` ensures the bean is not loaded unless certain conditions are fulfilled.

https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/java-dg-roles.html[_Configure IAM Roles for Amazon EC2_]
____
> If your application creates an AWS client using the create method, the client searches for credentials using the default credentials provider chain, in the following order:

> * In the Java system properties: `aws.accessKeyId` and `aws.secretAccessKey`.
> * In system environment variables: `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
> * In the default credentials file (the location of this file varies by platform).
> * n the Amazon ECS environment variable: `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`.
> * In the instance profile credentials, which exist within the instance metadata associated with the IAM role for the EC2 instance.
____

[source,java]
.src/main/java/example/micronaut/AwsResourceAccessCondition.java
----
include::{sourceDir}/src/main/java/example/micronaut/AwsResourceAccessCondition.java[]
----

Add a test to verify the service is loaded:

[source,java]
.src/test/java/example/micronaut/AwsSesMailServiceTest.java
----
include::{sourceDir}/src/test/java/example/micronaut/AwsSesMailServiceTest.java[]
----
